//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverHistory
    {
        public int DriverID { get; set; }
        public string DriverName { get; set; }
        public string LicenseNo { get; set; }
        public System.DateTime LicenseIDate { get; set; }
        public System.DateTime LicenseEDate { get; set; }
        public string CNIC { get; set; }
        public string Mobile { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastActive { get; set; }
        public string Remarks { get; set; }
        public int CarrierID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string HistoryType { get; set; }
    }
}
